name: Validate Pull Request

on:
  pull_request_target:
    branches:
      - main

jobs:
  validate-pr:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      pull-requests: write

    steps:
      - name: Detect changed files
        uses: yumemi-inc/changed-files@50f2544ad88b4f274eace9689431b7281132304c  # pin@v3.2.0
        id: changes

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # pin@v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Checkout upstream
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # pin@v6.0.2
        with:
          path: upstream
          ref: main
          repository: ${{ github.event.pull_request.base.repo.full_name }}

      - name: Validate
        if: steps.changes.outputs.exists == 'true'
        uses: symbioticfi/metadata-validation-scripts@main
        with:
          files: ${{ steps.changes.outputs.files }}
          issue: ${{ github.event.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          chain-id: 11155111
          rpc-url: https://sepolia.infura.io/v3/${{ secrets.RPC_URL_TOKEN }}
          upstream-checkout-path: upstream
          network-registry: "0x7d03b7343bf8d5cec7c0c27ece084a20113d15c9"
          operator-registry: "0x6f75a4fff97326a00e52662d82ea4fde86a2c548"
          vault-registry: "0x407a039d94948484d356efb765b3c74382a050b4"
